################## yum ##################
- name: Update all packages to their latest version
  ansible.builtin.yum:
    name: "*"
    state: latest
- name: Install packages
  ansible.builtin.yum:
    name:
      - epel-release
      - 'dnf-command(config-manager)'
      - chrony
      - dnf-automatic
      - git
      - screen
      - vim
    state: latest
- name: Add gh-cli repo
  get_url:
    url: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo
- name: Install gh-cli
  ansible.builtin.yum:
    name: gh
    enablerepo: gh-cli
    state: latest
- name: Install browsers - RHEL8
  ansible.builtin.yum:
    name:
      - https://vault.centos.org/centos/8/PowerTools/x86_64/os/Packages/perl-NKF-2.1.4-8.el8.x86_64.rpm
      - https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/w/w3m-0.5.3-55.git20220429.el8.x86_64.rpm
      - https://vault.centos.org/centos/8/PowerTools/x86_64/os/Packages/lynx-2.8.9-2.el8.x86_64.rpm
    state: latest
  when: ansible_distribution_major_version == "8"
- name: Install browsers - RHEL9
  ansible.builtin.yum:
    name:
      - https://download-ib01.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/p/perl-NKF-2.1.4-23.el9.x86_64.rpm
      - https://download-ib01.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/w/w3m-0.5.3-55.git20220429.el9.x86_64.rpm
      - http://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/lynx-2.8.9-19.el9.x86_64.rpm
    state: latest
  when: ansible_distribution_major_version == "9"
- name: Edit /etc/dnf/automatic.conf
  ansible.builtin.replace:
    path: /etc/dnf/automatic.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: true
  loop:
    - {regexp: '^apply_updates', replace: '#apply_updates'}
    - {regexp: '^download_updates', replace: '#download_updates'}
    - {regexp: '^email_from', replace: '#email_from'}
    - {regexp: '^email_to', replace: '#email_to'}
    - {regexp: '^email_host', replace: '#email_host'}
- name: Edit /etc/dnf/automatic.conf
  ansible.builtin.blockinfile:
    path: /etc/dnf/automatic.conf
    backup: true
    block: |
      apply_updates = yes
      download_updates = yes
- name: Enable and restart dnf-automatic
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ item }}"
    state: restarted
  with_items:
    - dnf-automatic.timer
    - dnf-automatic.service
################## bashrc ##################
- name: Copy /etc/profile.d/bashrc.sh
  ansible.builtin.copy:
    src: ../files/bashrc.sh
    dest: /etc/profile.d/bashrc.sh
    backup: true
################## chrony ##################
- name: Edit /etc/chrony.conf
  ansible.builtin.replace:
    path: /etc/chrony.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: true
  loop:
    - {regexp: '^server', replace: '#server'}
    - {regexp: '^pool', replace: '#pool'}
- name: Edit /etc/chrony.conf
  ansible.builtin.blockinfile:
    path: /etc/chrony.conf
    backup: true
    block: |
      server 0.jp.pool.ntp.org iburst
      server 1.jp.pool.ntp.org iburst
      server 2.jp.pool.ntp.org iburst
      server 3.jp.pool.ntp.org iburst
- name: Enable and restart service chronyd
  ansible.builtin.systemd:
    enabled: yes
    name: chronyd
    state: restarted
- name: Permit traffic in default zone for ntp service
  ansible.posix.firewalld:
    service: ntp
    permanent: yes
    state: enabled
################## Git ##################
- name: Git config - name
  ansible.builtin.git_config:
    name: user.name
    scope: global
    value: "{{ GIT_USER_NAME }}"
- name: Git config - email
  ansible.builtin.git_config:
    name: user.email
    scope: global
    value: "{{ GIT_USER_EMAIL }}"
################## screenrc ##################
- name: Copy /etc/screenrc
  ansible.builtin.copy:
    src: ../files/screenrc
    dest: /etc/screenrc
    backup: true
################## sysctl ##################
- name: Edit /etc/sysctl.conf
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    backup: true
    block: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
################## vimrc ##################
- name: Copy /etc/vimrc
  ansible.builtin.copy:
    src: ../files/vimrc
    dest: /etc/vimrc
    backup: true
